### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/modern-react#2]
Hey @sophiebits, @acdlite, and @gaearon 👋

I'm planning on using this for teaching material to teach PayPal engineers as well as create workshops and video material about cool stuff coming in React 16.7.0 (after you've announced the features of course). **All the material I develop for this initial release will be available for people to learn from for free** :)

If you could please review the code in https://github.com/kentcdodds/modern-react/tree/master/src/exercises-final to make sure that I'm not doing something odd/wrong with these features that would be really helpful! I want to make sure that when these features are released there's some material out there for people to learn about them.

If you want to run this stuff, you can run the `setup` script and then copy over the builds of React that you have with these features.

**Comment by kentcdodds** [comment]
Oh, also, I'm currently getting into an infinite loop in the Suspense stuff.

Here's the block of code that's triggering the infinite loop in the test:

https://github.com/kentcdodds/modern-react/blob/5b2e2320dfd17b33894f8b6201eda05acbfcf50a/src/__tests__/11.js#L28-L33

If you make this return `Promise.reject()` then you can reproduce the infinite loop in the app:

https://github.com/kentcdodds/modern-react/blob/5b2e2320dfd17b33894f8b6201eda05acbfcf50a/src/fetch-pokemon.js#L2

Help there would be super appreciated :)

Here's the code for where that's all happening: https://github.com/kentcdodds/modern-react/blob/master/src/exercises-final/11.js

(Note: I _do_ plan to teach and recommend `react-cache` (see 12, 13, and 14), I just like to start as simple as possible so people understand what's going on fundamentally).

**Comment by kentcdodds** [comment]
Oh, and exercise 15 doesn't work yet because you can't currently use Hooks in `React.pure`. @acdlite mentioned that's an oversight and will be fixed, either way a review of that is appreciated as well :)

**Comment by sophiebits** [comment]
11.js: You probably want to cache the promise so you don't ever do two fetches for the same name. Would the error boundary and placeholder be better in Usage? Generally people err on the side of coupling Placeholders too tightly with individual fetches and we want to discourage that.

12.js/13.js: Best practices on passing down a cache are TBD and might change in the next two weeks.

14.js: Maybe teach React.lazy before other types of suspense? It's easier to wrap your head around I think.

**Comment by kentcdodds** [comment]
All great tips @sophiebits! Thank you!
