### ISSUE TITLE
src\exercises\03.js throwing error TypeError: (0 , _reactTestingLibrary.flushEffects) is not a function

### ISSUE THREAD

**Issue by barshopen** [kentcdodds/modern-react#4]
Continous to [this issue](https://github.com/kentcdodds/modern-react/issues/3) I'm getting error thrown at me saying flushEffects isn't an error. 
Without flushEffects() at line 19 my tests pass fine. 
I'm not familiar with react-testing-library so I don't know if it's issue with my env or a known issue. Can anyone shed light how I can fix it?

Thanks.

**Comment by kentcdodds** [comment]
Hi @barshopen, this repo is pretty old and I'm no longer maintaining it. You'd be better off with the [EpicReact.Dev](https://epicreact.dev) repos: https://github.com/topics/epicreact-dev

Sorry :-(
